### ISSUE TITLE
Question on tiling rasters for use with glcolorscale

### ISSUE THREAD

**Issue by smorford** [ihmeuw/leaflet.tilelayer.glcolorscale#1]
Hi, Thanks for developing this - looks really useful. 

I'm trying to implement your libraries on my own dataset. So far I've failed, and as much as I can gather from the error logs, it appears that my tiling regime is incorrect, as inspector is spitting out 404 errors for the tile pngs. I can see/project the tiles just fine if I add through L.tileLayer.

For tiling, I'm projecting the floating point raster to EPSG:3857 using gdalwarp and the using gdal2tile.py to tile (default settings). 

[I'm using your demo as a template](http://tnc.terra-analytics.net/sagenet/demo/index.html)

I'm wondering if I need to be using a different projection, or tiling by some other mechanism to get this to work. Thanks!

**Comment by davschne** [comment]
Hi! Thanks for trying this out; I'm sorry it's not working for you yet.

I opened your demo and tried to troubleshoot a little. I too am seeing the 404, both in the demo, and when I try to access the tiles directly (with URL like http://tnc.terra-analytics.net/sagenet/floating/5/5/10.png). I wonder if this may be due to server configuration?

I'd expect to see some sort of image when accessing a tile URL directly if the server is working correctly. Try, for instance, directly accessing one of the tiles from my demo, like: https://vizhub.healthdata.org/lbd/api/v1/themes/under5/schemas/mortality/map/raster/2/2/2.png?age_group=under5&location_id=0&measure=mortality&stat=mean&year=2000.

**Comment by davschne** [comment]
Closing this issue for now, because I don't think this is a problem with the library.
